trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

schedules:
  - cron: 0 0 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - master

variables:
  - name: checkoutPath
    value: ansible_collections/community/windows
  - name: fetchDepth
    value: 100

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.6.0

pool: Standard

stages:
  - stage: Sanity_devel
    name: Sanity devel
    dependsOn: []
    jobs:
      - template: templates/targets.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: Test
              test: sanity
  - stage: Sanity_2_10
    name: Sanity 2.10
    dependsOn: []
    jobs:
      - template: templates/targets.yml
        parameters:
          testFormat: 2.10/{0}
          targets:
            - name: Test
              test: sanity
  - stage: Units_devel
    name: Units devel
    dependsOn: []
    jobs:
      - template: templates/targets.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: Python
              test: units
  - stage: Units_2_10
    name: Units 2.10
    dependsOn: []
    jobs:
      - template: templates/targets.yml
        parameters:
          testFormat: 2.10/{0}
          targets:
            - name: Python
              test: units
  - stage: Windows_devel
    name: Windows devel
    dependsOn: []
    jobs:
      - template: templates/targets.yml
        parameters:
          jobFormat: windows_{0}
          nameFormat: Server {0}
          testFormat: devel/windows/{0}
          targets:
            - name: 2012
            - name: 2012-R2
            - name: 2016
            - name: 2019
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity_devel
      - Sanity_2_10
      - Units_devel
      - Units_2_10
      - Windows_devel
    jobs:
      - template: templates/coverage.yml
