trigger:
  - master

pool: Standard_DS1_v2
container: quay.io/ansible/ansible-base-test-container:1.6.0

steps:
  - checkout: self
    fetchDepth: 100
  - bash: docker ps
    displayName: Show Containers
