trigger:
  - master

pool:
  vmImage: ubuntu-latest

container: quay.io/ansible/ubuntu1804-test-container:1.17.0

steps:
  - checkout: self
    fetchDepth: 100
  - bash: |
      set -eu
      export TERM=linux
      sudo apt-get update -y
      sudo apt-get install docker.io python3.7 python3-pip -y --no-install-recommends
      sudo ln -s /usr/bin/python3 /usr/local/bin/python
      sudo ln -s /usr/bin/pip3 /usr/local/bin/pip
      sudo chmod 777 /var/run/docker.sock
      python3 -m pip install cryptography --user --disable-pip-version-check
    displayName: Prepare Environment
  - bash: env
    displayName: Show Environment
  - bash: cat /proc/self/cgroup
  - bash: cat /proc/self/cpuset
  - bash: cat /proc/self/mountinfo
  - bash: docker inspect $(basename $(cat /proc/self/cpuset))
    displayName: Show docker inspect
  - bash: docker ps | tee ${AGENT_TEMPDIRECTORY}/containers.txt
    displayName: Show Containers
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact
    inputs:
      targetPath: $(Agent.TempDirectory)/containers.txt
      artifactName: Containers
