trigger:
- master

pool: Standard_DS1_v2

jobs:
  - job: J001
    displayName: Job J001
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J002
    displayName: Job J002
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J003
    displayName: Job J003
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J004
    displayName: Job J004
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J005
    displayName: Job J005
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J006
    displayName: Job J006
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J007
    displayName: Job J007
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J008
    displayName: Job J008
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J009
    displayName: Job J009
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J010
    displayName: Job J010
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J011
    displayName: Job J011
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J012
    displayName: Job J012
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J013
    displayName: Job J013
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J014
    displayName: Job J014
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J015
    displayName: Job J015
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J016
    displayName: Job J016
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J017
    displayName: Job J017
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J018
    displayName: Job J018
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J019
    displayName: Job J019
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J020
    displayName: Job J020
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J021
    displayName: Job J021
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J022
    displayName: Job J022
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J023
    displayName: Job J023
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J024
    displayName: Job J024
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J025
    displayName: Job J025
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J026
    displayName: Job J026
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J027
    displayName: Job J027
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J028
    displayName: Job J028
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J029
    displayName: Job J029
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J030
    displayName: Job J030
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J031
    displayName: Job J031
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J032
    displayName: Job J032
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J033
    displayName: Job J033
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J034
    displayName: Job J034
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J035
    displayName: Job J035
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J036
    displayName: Job J036
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J037
    displayName: Job J037
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J038
    displayName: Job J038
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J039
    displayName: Job J039
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J040
    displayName: Job J040
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J041
    displayName: Job J041
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J042
    displayName: Job J042
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J043
    displayName: Job J043
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J044
    displayName: Job J044
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J045
    displayName: Job J045
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J046
    displayName: Job J046
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J047
    displayName: Job J047
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J048
    displayName: Job J048
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J049
    displayName: Job J049
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
  - job: J050
    displayName: Job J050
    steps:
      - script: echo Hello $(System.JobDisplayName)
        displayName: Hello
