trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: test
    displayName: ""
    strategy:
      matrix:
        One:
          test: one
        Two:
          test: two
    steps:
    - script: echo Hello $(test)
      displayName: Hello $(test)
