trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: |
      mkdir '$(Agent.TempDirectory)/coverage/'
      cd '$(Agent.TempDirectory)/coverage/'
      touch various=various=various=python-3.8=coverage.combined
      touch coverage-analyze-targets.json
    displayName: Mock Coverage Data
  - task: PublishPipelineArtifact@1
    displayName: Publish Coverage Data
    inputs:
      targetPath: '$(Agent.TempDirectory)/coverage/'
      artifactName: "Coverage $(System.JobAttempt) $(System.StageDisplayName) $(System.JobDisplayName)"
  - task: DownloadPipelineArtifact@2
    displayName: Download Coverage Data
    inputs:
      path: coverage/
      patterns: 'Coverage */*=coverage.combined'
  - bash: |
      pwd
      find coverage
    displayName: Show Coverage Data
