trigger:
 - master

pool: Experimental

jobs:
  - job: One
    steps:
      - script: sleep 60
        displayName: Sleep
  - job: Two
    steps:
      - script: sleep 60
        displayName: Sleep
  - job: Three
    steps:
      - script: sleep 60
        displayName: Sleep
