trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

schedules:
  - cron: 0 0 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - master

variables:
  - name: checkoutPath
    value: ansible_collections/community/general
  - name: fetchDepth
    value: 100

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.6.0

pool: Standard

stages:
  - template: templates/test-simple.yml
    parameters:
      stage: Sanity_devel
      name: Sanity devel
      targets:
        - name: Test 1
          test: sanity/1
        - name: Test 2
          test: sanity/2
        - name: Test 3
          test: sanity/3
        - name: Test 4
          test: sanity/4
        - name: Test extra
          test: sanity/extra
  - template: templates/test-simple.yml
    parameters:
      stage: Sanity_2_10
      name: Sanity 2.10
      targets:
        - name: Test 1
          test: sanity/1
        - name: Test 2
          test: sanity/2
        - name: Test 3
          test: sanity/3
        - name: Test 4
          test: sanity/4
  - template: templates/test-simple.yml
    parameters:
      stage: Sanity_2_9
      name: Sanity 2.9
      targets:
        - name: Test 1
          test: sanity/1
        - name: Test 2
          test: sanity/2
        - name: Test 3
          test: sanity/3
        - name: Test 4
          test: sanity/4
  - template: templates/test-simple.yml
    parameters:
      stage: Units_devel
      name: Units devel
      testFormat: '{0}/1'
      targets:
        - name: Python 2.6
          test: units/2.6
        - name: Python 2.7
          test: units/2.7
        - name: Python 3.5
          test: units/3.5
        - name: Python 3.6
          test: units/3.6
        - name: Python 3.7
          test: units/3.7
        - name: Python 3.8
          test: units/3.8
        - name: Python 3.9
          test: units/3.9
  - template: templates/test-simple.yml
    parameters:
      stage: Units_2_10
      name: Units 2.10
      testFormat: '{0}/1'
      targets:
        - name: Python 2.6
          test: units/2.6
        - name: Python 2.7
          test: units/2.7
        - name: Python 3.5
          test: units/3.5
        - name: Python 3.6
          test: units/3.6
        - name: Python 3.7
          test: units/3.7
        - name: Python 3.8
          test: units/3.8
        - name: Python 3.9
          test: units/3.9
  - template: templates/test-simple.yml
    parameters:
      stage: Units_2_9
      name: Units 2.9
      testFormat: '{0}/1'
      targets:
        - name: Python 2.6
          test: units/2.6
        - name: Python 2.7
          test: units/2.7
        - name: Python 3.5
          test: units/3.5
        - name: Python 3.6
          test: units/3.6
        - name: Python 3.7
          test: units/3.7
        - name: Python 3.8
          test: units/3.8
  - template: templates/test-simple-grouped.yml
    parameters:
      stage: Remote_devel
      name: Remote devel
      targets:
        - name: OS X 10.11
          test: osx/10.11
        - name: macOS 10.15
          test: macos/10.15
        - name: RHEL 7.8
          test: rhel/7.8
        - name: RHEL 8.2
          test: rhel/8.2
        - name: FreeBSD 11.1
          test: freebsd/11.1
        - name: FreeBSD 12.1
          test: freebsd/12.1
      groups:
        - 1
        - 2
        - 3
  - template: templates/test-simple-grouped.yml
    parameters:
      stage: Docker_devel
      name: Docker devel
      targets:
        - name: CentOS 6
          test: linux/centos6
        - name: CentOS 7
          test: linux/centos7
        - name: CentOS 8
          test: linux/centos8
        - name: Fedora 31
          test: linux/fedora31
        - name: Fedora 32
          test: linux/fedora32
        - name: openSUSE 15 py2
          test: linux/opensuse15py2
        - name: openSUSE 15 py3
          test: linux/opensuse15
        - name: Ubuntu 16.04
          test: linux/ubuntu1604
        - name: Ubuntu 18.04
          test: linux/ubuntu1804
      groups:
        - 1
        - 2
        - 3
  - template: templates/test-simple.yml
    parameters:
      stage: Cloud_devel
      name: Cloud devel
      testFormat: '{0}/1'
      targets:
        - name: Python 2.7
          test: cloud/2.7
        - name: Python 3.6
          test: cloud/3.6
  - template: templates/test-simple-grouped.yml
    parameters:
      stage: Remote_2_10
      name: Remote 2.10
      targets:
        - name: OS X 10.11
          test: osx/10.11
        - name: RHEL 8.2
          test: rhel/8.2
        - name: FreeBSD 12.1
          test: freebsd/12.1
      groups:
        - 1
        - 2
  - template: templates/test-simple-grouped.yml
    parameters:
      stage: Docker_2_10
      name: Docker 2.10
      targets:
        - name: CentOS 8
          test: linux/centos8
        - name: Fedora 32
          test: linux/fedora32
        - name: openSUSE 15 py3
          test: linux/opensuse15
      groups:
        - 2
        - 3
  - template: templates/test-simple.yml
    parameters:
      stage: Cloud_2_10
      name: Cloud 2.10
      testFormat: '{0}/1'
      targets:
        - name: Python 3.6
          test: cloud/3.6
  - template: templates/test-simple-grouped.yml
    parameters:
      stage: Remote_2_9
      name: Remote 2.9
      targets:
        - name: RHEL 8.2
          test: rhel/8.2
        - name: FreeBSD 12.0
          test: freebsd/12.0
      groups:
        - 1
        - 2
  - template: templates/test-simple-grouped.yml
    parameters:
      stage: Docker_2_9
      name: Docker 2.9
      targets:
        - name: CentOS 8
          test: linux/centos8
        - name: Fedora 31
          test: linux/fedora31
        - name: openSUSE 15 py3
          test: linux/opensuse15
      groups:
        - 2
        - 3
  - template: templates/test-simple.yml
    parameters:
      stage: Cloud_2_9
      name: Cloud 2.9
      testFormat: '{0}/1'
      targets:
        - name: Python 3.6
          test: cloud/3.6
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity_devel
      - Sanity_2_10
      - Sanity_2_9
      - Units_devel
      - Units_2_10
      - Units_2_9
      - Remote_devel
      - Docker_devel
      - Cloud_devel
      - Remote_2_10
      - Docker_2_10
      - Cloud_2_10
      - Remote_2_9
      - Docker_2_9
      - Cloud_2_9
    jobs:
      - template: templates/coverage.yml
