trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: normal
    displayName: Normal
    steps:
      - script: echo Hello World
        displayName: Hello
  - job: shallow_1
    displayName: Shallow 1
    steps:
      - checkout: self
        fetchDepth: 1
        displayName: Checkout
      - script: echo Hello World
        displayName: Hello
  - job: shallow_10
    displayName: Shallow 10
    steps:
      - checkout: self
        fetchDepth: 10
        displayName: Checkout
      - script: echo Hello World
        displayName: Hello
  - job: shallow_100
    displayName: Shallow 100
    steps:
      - checkout: self
        fetchDepth: 100
        displayName: Checkout
      - script: echo Hello World
        displayName: Hello
