trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

schedules:
  - cron: 0 0 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - master

variables:
  - name: checkoutPath
    value: ansible_collections/community/windows
  - name: fetchDepth
    value: 100

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.6.0

pool: Standard

stages:
  - template: templates/stage.yml
    parameters:
      stage: Sanity_devel
      name: Sanity devel
      testFormat: devel/{0}
      targets:
        - name: Test
          test: sanity
  - template: templates/stage.yml
    parameters:
      stage: Sanity_2_10
      name: Sanity 2.10
      testFormat: 2.10/{0}
      targets:
        - name: Test
          test: sanity
  - template: templates/stage.yml
    parameters:
      stage: Units_devel
      name: Units devel
      testFormat: devel/{0}
      targets:
        - name: Python
          test: units
  - template: templates/stage.yml
    parameters:
      stage: Units_2_10
      name: Units 2.10
      testFormat: 2.10/{0}
      targets:
        - name: Python
          test: units
  - template: templates/stage.yml
    parameters:
      stage: Windows_devel
      name: Windows devel
      testFormat: devel/{0}
      targets:
        - name: Server 2012
          test: windows/2012
        - name: Server 2012-R2
          test: windows/2012-R2
        - name: Server 2016
          test: windows/2016
        - name: Server 2019
          test: windows/2019
      groups:
        - 1
        - 2
        - 3
        - 4
        - 5
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity_devel
      - Sanity_2_10
      - Units_devel
      - Units_2_10
      - Windows_devel
    jobs:
      - template: templates/coverage.yml
