jobs:
  - job: Coverage
    displayName: Code Coverage
    container: default
    workspace:
      clean: all
    steps:
      - checkout: self
        fetchDepth: ${{variables.fetchDepth}}
        path: ${{variables.checkoutPath}}
      - bash: echo coverage
        displayName: Coverage
