parameters:
  - name: targets
    type: object
  - name: groups
    type: object
    default: []

  - name: jobFormat
    type: string
    default: "{0}"
  - name: nameFormat
    type: string
    default: "{0}"
  - name: testFormat
    type: string
    default: "{0}"

  - name: jobGroupFormat
    type: string
    default: "{0}_{{1}}"
  - name: nameGroupFormat
    type: string
    default: "{0} - {{1}}"
  - name: testGroupFormat
    type: string
    default: "{0}/{{1}}"

jobs:
  - template: jobs.yml
    parameters:
      jobs:
        - ${{ if eq(length(parameters.groups), 0) }}:
          - ${{ each target in parameters.targets }}:
            - job: ${{ format(parameters.jobFormat, coalesce(target.test, target.name)) }}
              name: ${{ format(parameters.nameFormat, coalesce(target.name, target.test)) }}
              test: ${{ format(parameters.testFormat, coalesce(target.test, target.name)) }}
        - ${{ if not(eq(length(parameters.groups), 0)) }}:
          - ${{ each group in parameters.groups }}:
            - ${{ each target in parameters.targets }}:
              - job: ${{ format(format(parameters.jobGroupFormat, parameters.jobFormat), coalesce(target.test, target.name), group) }}
                name: ${{ format(format(parameters.nameGroupFormat, parameters.nameFormat), coalesce(target.name, target.test), group) }}
                test: ${{ format(format(parameters.testGroupFormat, parameters.testFormat), coalesce(target.test, target.name), group) }}
