parameters:
  - name: stage
    type: string
  - name: jobs
    type: object

stages:
  - stage: ${{ parameters.stage }}
    displayName: ${{ parameters.stage }}
    dependsOn: []
    jobs:
      - ${{ each job in parameters.jobs }}:
        - job: ${{ replace(replace(replace(job.job, '/', '_'), '.', '_'), '-', '_') }}
          displayName: ${{ job.name }}
          container: default
          workspace:
            clean: all
          steps:
            - checkout: self
              fetchDepth: ${{variables.fetchDepth}}
              path: ${{variables.checkoutPath}}
            - bash: echo ${{ lower(job.test) }}
              displayName: Run Tests
