parameters:
  - name: stage
    type: string
  - name: name
    type: string
    default: ""
  - name: targets
    type: object
  - name: groups
    type: object

  - name: jobFormat
    type: string
    default: "{0}_{1}_{2}"
  - name: nameFormat
    type: string
    default: "{0} {1} - {2}"
  - name: testFormat
    type: string
    default: "{0}/{1}/{2}"
  - name: testReplaceVersionDot
    type: string
    default: "."

stages:
  - template: test.yml
    parameters:
      stage: ${{ parameters.stage }}
      name: ${{ parameters.name }}
      jobs:
        - ${{ each group in parameters.groups }}:
          - ${{ each target in parameters.targets }}:
            - ${{ each version in target.versions }}:
              - job: ${{ format(parameters.jobFormat, coalesce(target.test, target.name), replace(version, ' ', ''), group) }}
                name: ${{ format(parameters.nameFormat, target.name, version, group) }}
                test: ${{ format(parameters.testFormat, coalesce(target.test, target.name), replace(replace(version, ' ', ''), '.', parameters.testReplaceVersionDot), group) }}
