parameters:
  - name: stage
    type: string
  - name: targets
    type: object
  - name: groups
    type: object

  - name: jobFormat
    type: string
    default: "{0}_{1}_{2}"
  - name: nameFormat
    type: string
    default: "{0} {1} - {2}"
  - name: testFormat
    type: string
    default: "{0}/{1}/{2}"

stages:
  - template: test.yml
    parameters:
      stage: ${{ parameters.stage }}
      jobs:
        - ${{ each group in parameters.groups }}:
          - ${{ each target in parameters.targets }}:
            - ${{ each version in target.versions }}:
              - job: ${{ format(parameters.jobFormat, target.test, version, group) }}
                name: ${{ format(parameters.nameFormat, target.name, version, group) }}
                test: ${{ format(parameters.testFormat, target.test, version, group) }}
