parameters:
  - name: job
    type: string
  - name: name
    type: string
  - name: test
    type: string

jobs:
  - job: ${{ replace(replace(replace(parameters.job, '/', '_'), '.', '_'), '-', '_') }}
    displayName: ${{ parameters.name }}
    container: default
    workspace:
      clean: all
    steps:
      - checkout: self
        fetchDepth: ${{variables.fetchDepth}}
        path: ${{variables.checkoutPath}}
      - bash: echo ${{ parameters.test }}
        displayName: Run Tests
