parameters:
  - name: stage
    type: string
  - name: targets
    type: object
  - name: groups
    type: object

  - name: jobFormat
    type: string
    default: "{0}_{1}"
  - name: nameFormat
    type: string
    default: "{0} - {1}"
  - name: testFormat
    type: string
    default: "{0}/{1}"

stages:
  - template: test.yml
    parameters:
      stage: ${{ parameters.stage }}
      jobs:
        - ${{ each group in parameters.groups }}:
          - ${{ each target in parameters.targets }}:
            - job: ${{ format(parameters.jobFormat, target.test, group) }}
              name: ${{ format(parameters.nameFormat, target.name, group) }}
              test: ${{ format(parameters.testFormat, target.test, group) }}
