parameters:
  - name: stage
    type: string
  - name: targets
    type: object

  - name: jobFormat
    type: string
    default: "{0}"
  - name: nameFormat
    type: string
    default: "{0}"
  - name: testFormat
    type: string
    default: "{0}"

stages:
  - template: test.yml
    parameters:
      stage: ${{ parameters.stage }}
      jobs:
        - ${{ each target in parameters.targets }}:
          - job: ${{ format(parameters.jobFormat, target.test) }}
            name: ${{ format(parameters.nameFormat, target.name) }}
            test: ${{ format(parameters.testFormat, target.test) }}
