parameters:
  - name: stage
    type: string
  - name: targets
    type: object

  - name: jobFormat
    type: string
    default: "{0}_{1}"
  - name: nameFormat
    type: string
    default: "{0} {1}"
  - name: testFormat
    type: string
    default: "{0}/{1}"

stages:
  - template: test.yml
    parameters:
      stage: ${{ parameters.stage }}
      jobs:
        - ${{ each target in parameters.targets }}:
          - ${{ each version in target.versions }}:
            - job: ${{ format(parameters.jobFormat, target.test, version) }}
              name: ${{ format(parameters.nameFormat, target.name, version) }}
              test: ${{ format(parameters.testFormat, target.test, version) }}
